trigger:
 - main

pool:
   vmImage: 'ubuntu-latest' 

variables:
   imageName: 'pipelines-python-docker'

steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: app/Dockerfile