trigger:
 - main

pool:
   vmImage: 'ubuntu-latest' 

variables:
   imageName: 'pipelines-python-docker'

steps:
     - task: Docker@2
       inputs:
         containerRegistry: 'Docker hub'
         repository: 'c100/azure-container'
         command: 'buildAndPush'
         Dockerfile: 'Dockerfile'

     - task: SSH@0
       inputs:
            sshEndpoint: 'Digital Ocean Droplet'
            runOptions: 'commands'
            commands: 'docker pull c100/azure-container:39'
            readyTimeout: '20000'