trigger:
 - main

pool:
   vmImage: 'ubuntu-latest' 

variables:
   imageName: 'pipelines-python-docker'

steps:
     - task: Docker@2
       inputs:
         containerRegistry: 'Docker hub'
         repository: 'c100/azure-container'
         command: 'buildAndPush'
         Dockerfile: 'Dockerfile'